sudo: required

language: php

php:
  - 5.5
  - 5.6

services:
  - docker

before_install:
- docker pull aerospike/aerospike-server
- docker run -tid --name aerospike -p 3000:3000 -p 3001:3001 -p 3002:3002 -p 3003:3003 aerospike/aerospike-server
- docker ps -a

before_script:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
